from pathlib import Path
import json,html
root=Path(__file__).parent;dist=root/'dist'
projects=[
{'id':'cascade','area':'vision','label':'Visual learning','title':'From vertebra segmentation to fracture classification','paper':'A Two-Stage Approach for the Identification and Classification of Osteoporotic Vertebral Compression Fractures','venue':'Medical Physics','year':'2026','status':'Published','authors':'Yilin Wang*, <strong>Siyu Chen*</strong>, Hongwei Zhuang*, et al.','role':'Project leader · Co-first author','image':'cascade','alt':'Two-stage framework connecting enhanced DeepLabv3+ vertebral segmentation and fracture classification.','description':'A two-stage X-ray pipeline separates vertebral segmentation from fracture classification, supporting both fracture identification and differentiation of new and old fractures.','contribution':'Developed an enhanced DeepLabv3+ segmentation module and a downstream classification pipeline for binary and three-class tasks.','result':'Binary AP 72.90 and three-class AP 50.16, compared with 53.51 and 39.59 for single-stage baselines.','url':'https://aapm.onlinelibrary.wiley.com/doi/abs/10.1002/mp.70479','extra':[('dataset','Construction of the classification dataset')]},
{'id':'vertex','area':'vision','label':'Visual learning','title':'VerteX-ID: multi-task fracture detection','paper':'VerteX-ID: A Multi-Task Learning Framework for Osteoporotic Compression Fracture Detection','venue':'IISE Transactions on Healthcare Systems Engineering','year':'2026','status':'Under review','authors':'Yilin Wang*, <strong>Siyu Chen*</strong>, Hongwei Zhuang*, et al.','role':'Co-first author','image':'vertex','alt':'Overview of the VerteX-ID multi-task framework with image enhancement and vertebral analysis.','description':'A multi-task learning framework for osteoporotic compression fracture detection, combining image enhancement and dedicated segmentation and classification components.','contribution':'Co-first-author research on learning from vertebral X-rays, with the ConDSeg and SCTNet architectures shown in the accompanying project figures.','result':None,'url':None,'extra':[('conds','ConDSeg architecture'),('sctnet','SCTNet architecture')]},
{'id':'dvt','area':'prediction','label':'Interpretable prediction','title':'Interpretable preoperative DVT risk stratification','paper':'An interpretable machine learning framework for preoperative deep vein thrombosis risk stratification based on thrombus size in fracture patients','venue':'Scientific Reports','year':'2026','status':'Under review','authors':'Yilin Wang*, <strong>Siyu Chen*</strong>, et al.','role':'Project leader · Co-first author','image':'dvt','alt':'DVT study workflow showing risk groups, feature selection, machine learning, and SHAP interpretation.','description':'A three-level risk stratification framework based on thrombus size, using 62 clinical variables from 1,216 fracture patients.','contribution':'Combined LASSO feature selection, CatBoost, SMOTE, and SHAP analysis to connect predictive performance with clinical interpretation.','result':'Reported test performance: 96.67% accuracy, 96.67% F1-score, and 98.94% AUC-ROC using 41 selected features.','url':None,'extra':[]},
{'id':'transfer','area':'vision','label':'Visual learning','title':'Transfer learning with limited, low-quality X-rays','paper':'Identifying acute thoracolumbar vertebral compression fractures from low-quality small-sample X-ray images: a transfer learning-based approach','venue':'IEEE Journal of Biomedical and Health Informatics','year':'2025','status':'Published','authors':'Yilin Wang*, Weijun Li*, <strong>Siyu Chen*</strong>, et al.','role':'Project leader · Co-first author','image':'transfer','alt':'Graphical abstract of the transfer learning pipeline integrating X-ray features, ViTDet, and Faster R-CNN.','description':'Investigating acute thoracolumbar vertebral compression fracture identification under small-sample and low-image-quality constraints.','contribution':'Integrated edge and texture features with ViTDet and Faster R-CNN to study transfer learning in a challenging clinical imaging setting.','result':'Approximately 33% of acute fracture images correctly classified by the model versus 27% in manual classification in the reported experiment.','url':'https://ieeexplore.ieee.org/abstract/document/11265857','extra':[]},
{'id':'umfcc','area':'signals','label':'Signal representations','title':'Listening to xylem cavitation with U-MFCC','paper':'Waveform purification of ultrasonic signals from xylem cavitation in tree species based on U-MFCC feature extraction and voiceprint recognition models','venue':'Computers and Electronics in Agriculture','year':'2025','status':'Published','authors':'<strong>Siyu Chen</strong>, et al.','role':'Project leader · First author','image':'umfcc','alt':'U-MFCC feature extraction with adapted Mel filters, IDCT, feature ranking, and PCA.','description':'Adapting voiceprint recognition methods to purify ultrasonic cavitation waveforms collected from two tree species.','contribution':'Developed U-MFCC with adapted Mel filter banks, IDCT, F-ratio feature selection, and PCA; evaluated ECAPA-TDNN, CAM++, and ERes2Net.','result':'The workflow selects 100 feature dimensions and reduces them to 40 with PCA for downstream waveform recognition.','url':'https://www.sciencedirect.com/science/article/pii/S0168169925009470','extra':[('cavitation','Cavitation signal acquisition setup')]},
{'id':'seeds','area':'vision','label':'Visual learning','title':'Seeing internal seed cracks without destruction','paper':'Soft X-ray image recognition and classification of maize seed cracks based on image enhancement and optimized YOLOv8 model','venue':'Computers and Electronics in Agriculture','year':'2024','status':'Published','authors':'<strong>Siyu Chen</strong>, et al.','role':'Project leader · First author','image':'seeds','alt':'Optimized YOLOv8 architecture for recognizing internal cracks in maize seeds.','description':'Non-destructive inspection of internal cracks in Zhengdan 958 maize seeds using soft X-ray imaging and an optimized YOLOv8 model.','contribution':'Combined wavelet denoising, image standardization, bilateral filtering, and Laplacian sharpening with object detection.','result':None,'url':'https://www.sciencedirect.com/science/article/pii/S0168169923008633','extra':[('seed-enhancement','Image enhancement and grayscale distributions')]}
]
# Stages follow research dates, not the journal publication year.
project_stages = {
 'cascade': ('ra', 'RA research', 'Jul–Oct 2025'),
 'vertex': ('ra', 'RA research', None),
 'dvt': ('ra', 'RA research & follow-up', 'Jan–Apr 2026'),
 'transfer': ('ra', 'RA research', 'Mar–Aug 2025'),
 'umfcc': ('early', 'Post-graduation continuation', 'Jul–Dec 2024'),
 'seeds': ('early', 'Undergraduate research', 'Aug–Dec 2023'),
}
for project in projects:
 project['stage'], project['stage_label'], project['research_dates'] = project_stages[project['id']]

(root/'content').mkdir(exist_ok=True)
(root/'content/research.json').write_text(json.dumps(projects,indent=2,ensure_ascii=False))

journal_metrics = {
 'Computers and Electronics in Agriculture': {'value': '10.3', 'year': '2025', 'source': 'https://www.bioxbio.com/journal/COMPUT-ELECTRON-AGR', 'publisher_source': 'https://www.sciencedirect.com/browse/calls-for-papers?subject=computer-science'},
 'IEEE Journal of Biomedical and Health Informatics': {'value': '7.7', 'year': '2025', 'source': 'https://www.bioxbio.com/journal/IEEE-J-BIOMED-HEALTH'}
}
(root/'content/journal-metrics.json').write_text(json.dumps(journal_metrics, indent=2))

def impact_badge(venue):
 metric = journal_metrics.get(venue)
 if not metric:
  return ''
 return f' <a class="impact-factor" href="{metric["source"]}" target="_blank" rel="noopener" title="Journal Impact Factor · view source">IF: {metric["value"]}</a>'

def fig(image,caption):
 return f'<a class="figure-link" href="assets/{image}.webp" target="_blank" rel="noopener"><img src="assets/{image}.webp" alt="{html.escape(caption)}" loading="lazy"><span>View full-size figure</span></a>'

cards=[]
for p in projects:
 extras=''.join(f'<figure>{fig(i,c)}<figcaption>{c}</figcaption></figure>' for i,c in p['extra'])
 cards.append(f'''<article class="research-card" id="{p['id']}" data-area="{p['area']}">
 <div class="project-figure">{fig(p['image'],p['alt'])}<p class="figure-caption">{p['venue']} · {p['year']}{impact_badge(p['venue'])}</p></div>
 <div class="project-copy"><div class="eyebrow">{p['label']} <span class="status {'review' if p['status']=='Under review' else ''}">{p['status']}</span></div>
 <h3>{p['title']}</h3><p class="stage-label">{p['stage_label']}{' · '+p['research_dates'] if p['research_dates'] else ''}</p><p class="role">{p['role']}</p><p>{p['description']}</p>
 <details><summary>Contributions &amp; study details</summary><div class="detail-content"><p>{p['contribution']}</p>{'<p><strong>Study result.</strong> '+p['result']+'</p>' if p['result'] else ''}{extras}</div></details>
 <div class="project-links">{f'<a href="{p["url"]}" target="_blank" rel="noopener">Read paper <span aria-hidden="true">↗</span></a>' if p['url'] else '<span class="muted">Manuscript under review</span>'}</div></div></article>''')

def pubs(status, stage):
 return ''.join(f'''<article class="pub"><div class="pub-year">{p['year']}</div><div><h4>{f'<a href="{p["url"]}" target="_blank" rel="noopener">{p["paper"]}</a>' if p['url'] else p['paper']}</h4><p>{p['authors']}</p><p class="pub-stage">{p['stage_label']}{' · '+p['research_dates'] if p['research_dates'] else ''}</p><p class="venue">{'Submitted to ' if status=='Under review' else ''}{p['venue']}{impact_badge(p['venue'])}{' · <span class="review-text">Under review</span>' if status=='Under review' else ''}</p></div></article>''' for p in projects if p['status']==status and p['stage']==stage)

page='''<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Siyu Chen — AI for real-world sensing, with a focus on representation learning and intelligent analysis of noisy visual and sensory data. Seeking Fall 2027 PhD opportunities."><meta name="theme-color" content="#183f62"><meta property="og:title" content="Siyu Chen | AI for Real-World Sensing"><meta property="og:description" content="Representation learning and intelligent analysis of noisy visual and sensory data. Fall 2027 PhD applicant."><meta property="og:type" content="website"><title>Siyu Chen | AI for Real-World Sensing</title><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%23183f62'/%3E%3Ctext x='32' y='43' text-anchor='middle' font-family='Georgia' font-size='34' fill='white'%3ESC%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="styles.css"><script src="script.js" defer></script></head>
<body><a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><div class="header-inner"><a class="wordmark" href="#about">Siyu Chen<span class="wordmark-cn" lang="zh">陈思宇</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu</button><nav id="navigation" aria-label="Main navigation"><a href="#about">About</a><a href="#research">Research</a><a href="#publications">Publications</a><a href="#background">Background</a><a href="assets/Siyu-Chen-CV.pdf" download>CV <span class="file-type">PDF</span></a></nav></div></header>
<div class="layout"><aside class="profile"><img class="portrait" src="assets/portrait.webp" alt="Portrait of Siyu Chen" width="600" height="840" fetchpriority="high"><h1>Siyu Chen</h1><p class="chinese-name" lang="zh">陈思宇</p><p class="profile-title">AI for Real-World Sensing</p><p class="profile-affiliation">Research experience at<br><strong>Tsinghua University</strong><br>Industrial Engineering</p><div class="profile-links"><a href="mailto:scanlonchan@gmail.com">Email</a><a href="https://scholar.google.com/citations?view_op=list_works&amp;hl=zh-CN&amp;user=1JGwn6IAAAAJ" target="_blank" rel="noopener">Google Scholar</a><a href="assets/Siyu-Chen-CV.pdf" download>Download CV (PDF)</a></div><div class="sidebar-topics"><h2>Research interests</h2><p>Visual &amp; sensory representations<br>Learning with limited data<br>Multi-task &amp; transfer learning<br>Interpretable prediction</p></div><a class="email-address" href="mailto:scanlonchan@gmail.com">scanlonchan@gmail.com</a></aside>
<main id="main"><section id="about" class="about"><div class="section-kicker">About me</div><h2>Learning useful representations<br class="wide-only"> from noisy images and signals.</h2><p class="lead">My research focuses on <strong>representation learning and intelligent analysis of noisy visual and sensory data</strong>. I am interested in how domain-informed representations, transfer learning, and multi-task learning can support prediction when data are limited or imperfect. My work explores these questions through X-ray image analysis, acoustic signal recognition, and interpretable risk modeling.</p><p>I received my B.E. in Electronic Information Science and Technology from <strong>Beijing Forestry University</strong> in 2024. From January 2025 to March 2026, I was a research assistant in the Department of Industrial Engineering at <strong>Tsinghua University</strong>, mentored by Xiwen Bai.</p><div class="opportunity"><span class="opportunity-label">FALL 2027 · PhD opportunities</span><p>I am seeking PhD opportunities for Fall 2027. I hope to develop methods for learning from real-world images and signals, with an emphasis on useful representations, data-efficient learning, and interpretable predictions that support domain experts.</p><a href="mailto:scanlonchan@gmail.com">Get in touch</a></div><div class="research-map"><div><span>01</span><h3>Representation learning</h3><p>Extracting task-relevant structure from images and signals.</p></div><div><span>02</span><h3>Data-efficient learning</h3><p>Transfer and multi-task learning with limited or imperfect data.</p></div><div><span>03</span><h3>Interpretable analysis</h3><p>Connecting model predictions with domain understanding.</p></div></div></section>
<section id="research"><div class="section-heading"><div><div class="section-kicker">A shared focus across real-world data</div><h2>Research highlights</h2></div><span class="section-count">06 studies</span></div><p class="section-intro">Across these studies, I combine domain knowledge with feature extraction, learned representations, and predictive models. The applications provide concrete settings for studying image quality, limited training data, and model interpretability. Each study is labeled by research stage; journal years indicate publication or submission year.</p><div class="filters" role="group" aria-label="Filter research by methodological focus"><button aria-pressed="true" data-filter="all">All research</button><button aria-pressed="false" data-filter="vision">Visual learning</button><button aria-pressed="false" data-filter="signals">Signal representations</button><button aria-pressed="false" data-filter="prediction">Interpretable prediction</button></div><p class="sr-only" id="filter-status" aria-live="polite"></p><div class="research-list">RESEARCH_CARDS</div><p class="study-note">Results describe the individual studies and their reported evaluation settings; they are not a cross-study comparison.</p></section>
<section id="publications"><div class="section-heading"><div><div class="section-kicker">Research record</div><h2>Publications &amp; manuscripts</h2></div><a class="text-link" href="https://scholar.google.com/citations?view_op=list_works&amp;hl=zh-CN&amp;user=1JGwn6IAAAAJ" target="_blank" rel="noopener">Google Scholar</a></div><p class="section-intro">Grouped by the stage in which the research was conducted. Years beside articles indicate publication or submission year. * Equal contribution / co-first authorship; author lists are abbreviated.</p>
<div class="publication-stage"><h3 class="subheading">Research assistant &amp; follow-up research</h3><p class="stage-context">Tsinghua University RA appointment: Jan 2025–Mar 2026. The DVT study continued through Apr 2026.</p><h4 class="publication-status">Published journal articles <span>2 · Co-first author</span></h4>RA_PUBLISHED_PAPERS<h4 class="publication-status">Manuscripts under review <span>2 · Co-first author</span></h4>RA_REVIEW_PAPERS</div>
<div class="publication-stage"><h3 class="subheading">Undergraduate &amp; continued research</h3><p class="stage-context">Seed imaging was conducted during my B.E. U-MFCC was a continuation in Jul–Dec 2024, after graduation and before my RA appointment.</p><h4 class="publication-status">Published journal articles <span>2 · First author</span></h4>EARLY_PUBLISHED_PAPERS</div></section>
<section id="background"><div class="section-kicker">Academic background</div><h2>Experience &amp; education</h2><div class="timeline"><article><div class="timeline-date">Jan 2025 – Mar 2026</div><h3>Research Assistant</h3><p><strong>Tsinghua University</strong> · Department of Industrial Engineering</p><p>Mentor: Xiwen Bai. Research on transfer learning, model cascades, and multi-task learning for image analysis, alongside feature extraction and decision-support system development.</p><p class="stage-output"><strong>Research outputs:</strong> Two published co-first-author papers (JBHI and Medical Physics), two co-first-author manuscripts under review (VerteX-ID and DVT), and a packaging patent application. The DVT project continued through April 2026.</p></article><article><div class="timeline-date">Jul–Dec 2024</div><h3>Continued research after graduation</h3><p>Developed U-MFCC for ultrasonic cavitation signal recognition before starting the RA appointment.</p><p class="stage-output"><strong>Research outputs:</strong> A first-author paper in Computers and Electronics in Agriculture and a related patent application, both published in 2025.</p></article><article><div class="timeline-date">Sep 2020 – Jul 2024</div><h3>B.E., Electronic Information Science and Technology</h3><p><strong>Beijing Forestry University</strong> · Beijing, China</p><p class="stage-output"><strong>Undergraduate outputs:</strong> A first-author seed-imaging paper in Computers and Electronics in Agriculture (2024), two seed-imaging patent applications (2023), and a plant-information software copyright.</p></article></div>
<h3 class="subheading">Engineering &amp; earlier projects</h3><div class="engineering"><article><span class="small-meta">RA period · Apr–Oct 2025 · Core working member</span><h4>Intelligent cargo packing</h4><p>Corporate collaboration with COSCO Shipping. Contributed to packing algorithms, system integration, and a 3D decision-support interface, including parallel task execution, monitoring, timeout handling, and multilingual support.</p></article><article><span class="small-meta">Undergraduate · 2022 · Sole owner</span><h4>Plant Information Retrieval and Export Platform</h4><p>Built an Android application for plant specimen information retrieval and directory export, using MVC, JSON, MMKV, and RecyclerView.</p><p class="small-meta">Software copyright: 2023SR0519773</p></article></div><details class="earlier-projects"><summary>Earlier experimental projects</summary><div class="earlier-grid"><article><img src="assets/sound.webp" alt="Sound localization experimental circuit" loading="lazy"><h4>Sound localization on a 2D plane</h4><p>Experimental circuit architect · 2022. Combined microphone amplifier modules, TOA/TDOA methods, and LabVIEW for sound source localization.</p></article><article><img src="assets/thermal.webp" alt="Physical model used in the vegetation thermal radiation project" loading="lazy"><h4>Vegetation &amp; thermal radiation</h4><p>Project leader · 2023–2024. Built a simplified Sun–atmosphere–Earth–universe experiment to investigate vegetation carbon and moisture storage.</p></article></div></details>
<div class="background-grid"><div><h3 class="subheading">Academic service</h3><p>Peer reviewer for:</p><ul class="plain-list"><li>IISE Transactions on Healthcare Systems Engineering <span>2025</span></li><li>Journal of Agricultural Science and Technology <span>2025</span></li><li>Molecular &amp; Cellular Biomechanics <span>2025</span></li><li>Artificial Intelligence in Agriculture <span>2024</span></li><li>Mathematical Biosciences and Engineering <span>2024</span></li></ul></div><div><h3 class="subheading">Skills &amp; recognition</h3><p><strong>Programming:</strong> Python, C, C++, Java</p><p><strong>Engineering:</strong> image and signal processing, application development, circuit design, microcontroller development</p><p><strong>Languages:</strong> Mandarin (native), English (TOEFL 5.0/6)</p><p><strong>Selected honor:</strong> Third prize, National College Students’ Physics Experiment Competition, 2022.</p><p><strong>Project leadership:</strong> College Student Innovation and Entrepreneurship Training Program, rated Excellent, 2022–2024.</p></div></div>
<details class="patents"><summary>Patents &amp; software by research stage</summary><p class="study-note">Published patent application identifiers are listed below; no grant status is implied. The groups follow the related research projects, rather than the application publication year.</p><h4 class="publication-status">RA research</h4><ul><li>A Method, Apparatus, Device, and Computer Storage Medium for Packaging — <strong>CN121317420A</strong></li></ul><h4 class="publication-status">Undergraduate research</h4><ul><li>Soft X-ray Imaging of Internal Cracks in Corn Seeds: YOLOv8 Neural Network Recognition Method — <strong>CN117218544A</strong></li><li>Automatic Detection Device for Internal Cracks in Corn Seeds Based on Soft X-ray Image Recognition — <strong>CN117299597A</strong></li><li>Plant Information Retrieval and Export Platform System — <strong>2023SR0519773</strong> (software copyright)</li></ul><h4 class="publication-status">Continued research after graduation</h4><ul><li>Ultrasonic Cavitation Signal Purification for Xylem and MFCC Feature Enhancement Extraction Method — <strong>CN120234602A</strong> (U-MFCC project; application published in 2025)</li></ul></details></section>
<section class="contact" id="contact"><div class="section-kicker">Let’s connect</div><h2>Interested in a research conversation?</h2><p>I welcome conversations about Fall 2027 PhD opportunities in representation learning, visual and sensory data analysis, and AI for real-world decision support.</p><a href="mailto:scanlonchan@gmail.com">scanlonchan@gmail.com</a></section><footer><p>© 2026 Siyu Chen · Updated October 2026</p><p>Design inspired by <a href="https://github.com/xyjoey/PRISM" target="_blank" rel="noopener">PRISM</a></p></footer></main></div></body></html>'''
(dist/'index.html').write_text(page.replace('RESEARCH_CARDS',''.join(cards)).replace('RA_PUBLISHED_PAPERS',pubs('Published','ra')).replace('RA_REVIEW_PAPERS',pubs('Under review','ra')).replace('EARLY_PUBLISHED_PAPERS',pubs('Published','early')))
if (root/'.openai/hosting.json').exists():
 manifest=json.loads((root/'.openai/hosting.json').read_text());manifest['static']={'directory':'dist'};(root/'.openai/hosting.json').write_text(json.dumps(manifest,indent=2))
